server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TalentSourcingSystemDb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      CORS:
        filter:
          enabled: true
          allowedOrigins: "*"
          allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
          allowedHeaders: "Content-Type, Accept, X-Requested-With, remember-me"
          exposedHeaders: "Access-Control-Allow-Origin, Access-Control-Allow-Credentials"
          allowCredentials: true
          maxAge: 3600

